# Generated by Django 3.2.12 on 2022-06-26 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCounselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('problem', models.CharField(blank=True, max_length=512, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('is_assigned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('meeting_preference', models.CharField(blank=True, max_length=8, null=True)),
                ('purpose', models.TextField(blank=True, max_length=512, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usercounselling')),
            ],
        ),
    ]
