# Generated by Django 4.0.5 on 2022-06-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_doctor_phone'),
        ('userprofile', '0008_remove_doctor_id_alter_doctor_user'),
    ]

    operations = [
    ]
